#!/bin/sh

bm_dir="${XDG_DATA_HOME:-"${HOME}/.local/share"}"
bm="${bm_dir}/bookmarks"
[ ! -d "$bm_dir" ] && mkdir -p "${bm_dir}"
[ ! -f "$bm" ] && touch "${bm}"

bm_list() {
    sed -e '/^$/d' -e '/^#/d' "${bm}" | sort
}

bm_add() {
    url=$(printf "" | dmenu -p "Enter URL:")
    des=$(printf "" | dmenu -p "Enter Description:")

    [ -z "$url" ] && return 1
    [ -z "$des" ] && echo "${url}" >> "${bm}" && return 0
    echo "${des} - ${url}" >> "${bm}"
}

bm_delete() {
    bookmark="$(bm_list | dmenu)"
    [ -z "$bookmark" ] && return 0
    tmp="$(sed -e "\|${bookmark}|d" "${bm}")"
    echo "${tmp}" > "${bm}"
}

cmd="$(printf "add\ndelete\n$(bm_list)\n" | dmenu | awk '{print $(NF)}')"
case "$cmd" in
    add | delete) bm_"${cmd}" ;;
    *) xdg-open "${cmd}" > /dev/null ;;
esac
