#!/bin/sh

pgrep -x mpd > /dev/null || {
    ans="$(printf "yes\nno" | dmenu -p "MPD is not running, would you like to start it?")"
    [ "$ans" = yes ] && mpd || exit 0
}

cmd="list
shuffle
next
prev
toggle
clear
settings"
[ -z "$1" ] &&
    cmd="$(printf "${cmd}" | dmenu)" ||
    cmd="${1}"

case "${cmd}" in
    shuffle | next | prev | toggle | clear)
        mpc "${cmd}"
        ;;
    settings)
        cmd="repeat: $(mpc status %repeat%)\nrandom: $(mpc status %random%)\nsingle: $(mpc status %single%)\nconsume: $(mpc status %consume%)"
        cmd="$(printf "${cmd}" | dmenu | awk -F : '{print $1}')"
        mpc "${cmd}"
        ;;
    list)
        play="$(mpc playlist)"
        [ -z "$play" ] && {
            playlist="$(mpc lsplaylist | dmenu)"
            [ -z "$playlist" ] && echo "No playlist has been chosen" && exit 0
            mpc clear && mpc add "${playlist}" && mpc play && exit 0
        } || {
            IFS=$(printf '\n\t')
            playlist="$(mpc playlist)"
            for song in ${playlist}; do
                num=$((num + 1))
                songs="${songs}${num} ${song}\n"
            done
            song="$(printf "${songs}" | dmenu | awk '{print $1}')"
            mpc play "${song}"
        }
        ;;
esac
