#!/bin/sh

root_dir="."
chmod_dir="755"
chmod_file="644"
depth="-maxdepth 1"

for _ in "$@"; do
    case "${1}" in
        -d)
            root_dir="${2}"
            shift
            ;;
        -pd)
            chmod_dir="${2}"
            shift
            ;;
        -pf)
            chmod_file="${2}"
            shift
            ;;
        -D)
            [ ! "$2" = "-1" ] &&
                depth="-maxdepth ${2}" ||
                unset depth
            shift
            ;;
        *) shift ;;
    esac
done

opts="${root_dir} ${depth}"

find ${opts} -type d -exec echo "D: {}" \; -exec chmod "${chmod_dir}" {} \;
find ${opts} -type f -exec echo "F: {}" \; -exec chmod "${chmod_file}" {} \;
